image: sikalabs/ci

variables:
  TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  IMAGE: $CI_REGISTRY_IMAGE:$TAG

stages:
  - build
  - deploy dev

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context .
      --dockerfile ./Dockerfile
      --destination $IMAGE

deploy dev:
  stage: deploy dev
  when: manual
  variables:
    CONTENT: "image: $IMAGE"
  script:
    - |
      curl --request PUT --header "PRIVATE-TOKEN: $ARGOCD_COMMITTER_TOKEN" --header "Content-Type: application/json" --data "{\"branch\": \"master\", \"author_email\": \"pss-ci-bot@gitlab.sikalabs.io\", \"author_name\": \"[bot] pss-ci-bot\", \"content\": \"$CONTENT\", \"commit_message\": \"[auto] feat: Update image using CI in $FILE\"}" --url "https://gitlab.sikalabs.com/api/v4/projects/614/repository/files/$FILE"
